#!/usr/bin/env python3
"""Generates the flame-silhouette masks used by the home page photo reveal:
  public/flame-mask.svg  (.sun-disc)  — ring of S-curved flame tongues
  public/char-mask.svg   (.char-ring) — wavy charred-edge silhouette
Run from the repo root: python3 scripts/flame-masks.py
"""
import math
from pathlib import Path

CENTER = 50.0


def rot(x, y, deg):
    """rotate (x, y) around the viewBox center"""
    th = math.radians(deg)
    dx, dy = x - CENTER, y - CENTER
    return (
        CENTER + dx * math.cos(th) - dy * math.sin(th),
        CENTER + dx * math.sin(th) + dy * math.cos(th),
    )


def tongue_path(deg, r_base, h, w, lean):
    """One flame tongue: an S-leaning teardrop sitting on the base circle at
    angle `deg`, pointing outward. Built in local coords (up = outward) with
    two cubic beziers, then rotated into place. h = height, w = base width,
    lean = sideways tip drift (sign controls the swirl direction).
    """
    bx, by = CENTER, CENTER - r_base  # base midpoint before rotation
    p = [
        (bx - w / 2, by),                              # base left
        (bx - w * 1.1, by - h * 0.42),                 # left bow (wide)
        (bx + lean * 0.2 - w * 0.5, by - h * 0.72),    # inflection toward tip
        (bx + lean, by - h),                           # tip
        (bx + lean * 0.45, by - h * 0.55),             # fall back inside
        (bx + w * 0.8, by - h * 0.18),                 # right bow
        (bx + w / 2, by),                              # base right
    ]
    r = [rot(x, y, deg) for x, y in p]
    return (
        f"M{r[0][0]:.1f} {r[0][1]:.1f}"
        f"C{r[1][0]:.1f} {r[1][1]:.1f} {r[2][0]:.1f} {r[2][1]:.1f} {r[3][0]:.1f} {r[3][1]:.1f}"
        f"C{r[4][0]:.1f} {r[4][1]:.1f} {r[5][0]:.1f} {r[5][1]:.1f} {r[6][0]:.1f} {r[6][1]:.1f}Z"
    )


def flame_mask():
    r_base = 35.0
    # height/width/lean pattern echoing the reference art: tall licks between
    # shorter ones, leans alternating so the ring reads as swirling
    pattern = [
        (14.0, 7.0, 5.5), (7.0, 5.5, -3.0), (11.0, 6.5, 4.5),
        (8.5, 6.0, -4.0), (13.5, 7.0, 6.0), (7.5, 5.5, -2.5),
        (10.5, 6.5, 5.0), (9.0, 6.0, -4.5), (13.0, 7.0, 5.5),
        (7.0, 5.5, -3.0), (11.5, 6.5, 4.0), (8.5, 6.0, -5.0),
        (14.0, 7.0, 5.0), (8.0, 5.5, -3.5),
    ]
    n = len(pattern)
    parts = [f'<circle cx="50" cy="50" r="{r_base + 1.5}" fill="#fff"/>']
    for i, (h, w, lean) in enumerate(pattern):
        deg = 360.0 * i / n
        parts.append(f'<path fill="#fff" d="{tongue_path(deg, r_base, h, w, lean)}"/>')
    return parts


def char_mask():
    pts = []
    n = 140
    for i in range(n):
        th = 2 * math.pi * i / n
        r = 42 + 3.5 * math.sin(6 * th + 1.7) + 2.2 * math.sin(11 * th + 0.4) + 1.2 * math.sin(17 * th + 3.1)
        r = min(r, 49.6)
        pts.append(f"{50 + r * math.cos(th):.1f} {50 + r * math.sin(th):.1f}")
    return [f'<path fill="#fff" d="M{"L".join(pts)}Z"/>']


def write(name, parts):
    svg = (
        "<!-- generated by scripts/flame-masks.py - do not edit by hand -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">\n  '
        + "\n  ".join(parts)
        + "\n</svg>\n"
    )
    Path(name).write_text(svg)
    print(f"wrote {name}")


if __name__ == "__main__":
    write("public/flame-mask.svg", flame_mask())
    write("public/char-mask.svg", char_mask())
