#!/usr/bin/env python3
"""Generates public/flame-ring.svg — the full-color fire ring used by the
home page photo reveal (.flame-ring). Everything is baked into one image
(cooling fire gradient + S-curved flame tongues) so the browser animates a
single static texture with compositor-only transforms.
Run from the repo root: python3 scripts/flame-ring.py
"""
import math
from pathlib import Path

CENTER = 50.0


def rot(x, y, deg):
    """rotate (x, y) around the viewBox center"""
    th = math.radians(deg)
    dx, dy = x - CENTER, y - CENTER
    return (
        CENTER + dx * math.cos(th) - dy * math.sin(th),
        CENTER + dx * math.sin(th) + dy * math.cos(th),
    )


def tongue_path(deg, r_base, h, w, lean):
    """One flame tongue: an S-leaning teardrop sitting on the base circle at
    angle `deg`, pointing outward. Built in local coords (up = outward) with
    two cubic beziers, then rotated into place. h = height, w = base width,
    lean = sideways tip drift (sign controls the swirl direction).
    """
    bx, by = CENTER, CENTER - r_base  # base midpoint before rotation
    p = [
        (bx - w / 2, by),                              # base left
        (bx - w * 1.1, by - h * 0.42),                 # left bow (wide)
        (bx + lean * 0.2 - w * 0.5, by - h * 0.72),    # inflection toward tip
        (bx + lean, by - h),                           # tip
        (bx + lean * 0.45, by - h * 0.55),             # fall back inside
        (bx + w * 0.8, by - h * 0.18),                 # right bow
        (bx + w / 2, by),                              # base right
    ]
    r = [rot(x, y, deg) for x, y in p]
    return (
        f"M{r[0][0]:.1f} {r[0][1]:.1f}"
        f"C{r[1][0]:.1f} {r[1][1]:.1f} {r[2][0]:.1f} {r[2][1]:.1f} {r[3][0]:.1f} {r[3][1]:.1f}"
        f"C{r[4][0]:.1f} {r[4][1]:.1f} {r[5][0]:.1f} {r[5][1]:.1f} {r[6][0]:.1f} {r[6][1]:.1f}Z"
    )


def build():
    r_base = 43.0
    # height/width/lean pattern echoing the reference art: tall licks between
    # shorter ones, leans alternating so the ring reads as swirling
    pattern = [
        (6.5, 5.0, 2.8), (3.5, 4.2, -1.6), (5.5, 4.8, 2.2),
        (4.0, 4.5, -2.0), (6.5, 5.0, 3.0), (3.8, 4.2, -1.4),
        (5.0, 4.8, 2.5), (4.2, 4.5, -2.2), (6.0, 5.0, 2.8),
        (3.5, 4.2, -1.6), (5.5, 4.8, 2.0), (4.0, 4.5, -2.5),
        (6.5, 5.0, 2.5), (3.8, 4.2, -1.8),
    ]
    n = len(pattern)
    # the fire lives entirely in the outer rim: the photo's clip edge sits
    # at ~83% of the element radius throughout the reveal (constant-ratio
    # animation), so the whole gold->orange->ember ramp is packed beyond it
    stops = [
        (0.00, "hsl(48 100% 85%)", 1.0),
        (0.74, "hsl(48 100% 80%)", 1.0),
        (0.82, "hsl(42 98% 62%)", 1.0),
        (0.88, "hsl(24 96% 55%)", 1.0),
        (0.93, "hsl(12 90% 48%)", 0.95),
        (0.965, "hsl(5 75% 38%)", 0.8),
        (0.99, "hsl(5 75% 38%)", 0.0),
    ]
    parts = ['<radialGradient id="fire" cx="50" cy="50" r="50" gradientUnits="userSpaceOnUse">']
    for off, color, op in stops:
        parts.append(f'  <stop offset="{off}" stop-color="{color}" stop-opacity="{op}"/>')
    parts.append("</radialGradient>")
    parts.append(f'<circle cx="50" cy="50" r="{r_base + 1.5}" fill="url(#fire)"/>')
    for i, (h, w, lean) in enumerate(pattern):
        deg = 360.0 * i / n
        parts.append(f'<path fill="url(#fire)" d="{tongue_path(deg, r_base, h, w, lean)}"/>')
    return parts


def write(name, parts):
    svg = (
        "<!-- generated by scripts/flame-ring.py - do not edit by hand -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">\n  '
        + "\n  ".join(parts)
        + "\n</svg>\n"
    )
    Path(name).write_text(svg)
    print(f"wrote {name}")


if __name__ == "__main__":
    write("public/flame-ring.svg", build())
